spring:
  application:
    name: springmaster
  profiles:
    default: ${APP_PROFILE:dev}

server:
  port: ${APP_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: ${APP_OPENAPI_PATH:/api-docs}
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: ${LOG_LEVEL:INFO}
